name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101 
    - name: Build Api
      run: dotnet build "Api/Api.csproj" --configuration Release --framework netcoreapp2.0
    - name: Build UnitTest
      run: dotnet build "UnitTestProject/UnitTestProject.csproj" --configuration Release --no-restore --framework netcoreapp3.1      
